<a href="https://colab.research.google.com/github/RChandana/ML/blob/main/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#Importing NumPy and printing version number

import numpy as np
print(np.__version__)

1.21.6


In [12]:
#Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

import numpy as np
arr_1 = np.array([10, 20, 30, 40, 50])
arr_2 = np.array([60, 70, 80, 90, 100])
print(arr_1 + arr_2)
print(np.multiply(1, arr_2))

[ 70  90 110 130 150]
[ 60  70  80  90 100]


In [31]:
# Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

array = np.array([1, 2, 3, 4, 5, 6, 7])
print([array*5])

[array([ 5, 10, 15, 20, 25, 30, 35])]


In [32]:
#How to create an identity  matrix of 5*5 dim?

def identity(n) : 
  identity = [[0 for x in range(n)] for y in range(n)]
  for i in range(0, n):
    identity[i][i] = 1
  return identity
print(identity(5)) 

[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]


In [14]:
# Convert a 1-D array to a 3-D array.

import numpy as np
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
new_array = array.reshape(3, 3, 1)
print(new_array)

[[[10]
  [20]
  [30]]

 [[40]
  [50]
  [60]]

 [[70]
  [80]
  [90]]]


In [15]:
# Convert all the elements of a numpy array from float to integer datatype

import numpy as np
array = np.array([12.6, 220.43, 5.0, 34.40, 65.77, 60, 123.50])
print(array.astype(int))

[ 12 220   5  34  65  60 123]


In [16]:
# Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array.

import numpy as np
array = np.array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1])
print(array.astype(dtype = bool))

[ True  True False  True False False  True False  True  True False False
 False  True  True]


In [17]:
# Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)?

arr_1 = np.array([10, 20, 30, 40, 50, 60])
arr_2 = np.array([60, 70, 80, 90, 100, 0])
print(np.concatenate((arr_1, arr_2)))

[ 10  20  30  40  50  60  60  70  80  90 100   0]


In [18]:
# Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)?

arr_1 = np.array([10, 20, 30, 40, 50, 60])
arr_2 = np.array([60, 70, 80, 90, 100, 0])
print(np.vstack((arr_1, arr_2)))

[[ 10  20  30  40  50  60]
 [ 60  70  80  90 100   0]]


In [19]:
#Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....?

import numpy as np
array = np.arange(100)
print(array[0 : 100 : 2])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [20]:
#From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match?

import numpy as np
arr_1 = np.array([10, 20, 30, 40, 50, 60])
arr_2 = np.array([70, 20, 80, 90, 50, 0])
x = np.where(arr_1 == arr_2)
print(x)

(array([1, 4]),)


In [21]:
#Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)?

array = np.arange(101)
print("The Intial array is : ", array)
print("\nThe Final array is :", array[0:101:5])

The Intial array is :  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]

The Final array is : [  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [23]:
#Output an array by repeating a smaller array of 2 dimensions, 10 times?

array_1 = np.array([10, 20, 30, 40, 50])
np.repeat(array_1, 10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [24]:
#Output a 3-by-3 array of random numbers following normal distribution

array = np.random.random((3, 3, 3))
print("The random 3X3 array using normal ditrubution is \n:", array)

The random 3X3 array using normal ditrubution is 
: [[[0.03304528 0.82196719 0.35341205]
  [0.86487851 0.40438357 0.92405559]
  [0.60043221 0.52552966 0.89443931]]

 [[0.84633108 0.51553873 0.26955623]
  [0.56579486 0.18549477 0.47645078]
  [0.29982669 0.68099524 0.18023438]]

 [[0.42231981 0.52962553 0.65592342]
  [0.12328868 0.08413025 0.39975087]
  [0.42159085 0.86325149 0.30950838]]]


In [25]:
#Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays

array = np.arange(10, 34, 1).reshape(8,3) 
output = np.split(array,4)
print(output)

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [27]:
#Print max from axis 0 and min from axis 1 from a 2-D array?

import numpy as np
array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Maximum element for axis 0 is : ", np.amax(array, 0))
print("Minimum element for axis 1 is : ", np.amin(array, 1))

Maximum element for axis 0 is :  [70 80 90]
Minimum element for axis 1 is :  [10 40 70]
